#!/bin/bash

TEMPDIR=`mktemp -d`
cd $TEMPDIR
wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
unzip pup_v0.4.0_linux_amd64.zip
chmod +x pup
mv pup /usr/bin/pup
